version: '3.9'

services: 
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/internals/migrations/000001_init.up.sql
      - db-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    expose: 
      - "6379"
    ports:
      - "6379:6379"
  nats-streaming: 
    image: "nats-streaming:0.17.0"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "./nats-streaming-1:/data"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
      - redis
volumes:
  db-data: