db:
  port: "5432"
  name: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  sslmode: "disable"
server: 
  port: "8080"
  host: "localhost"
redis: 
  host: "localhost"
  port: "6379"
  password: ""
